#!/bin/bash

ES_URL="http://localhost:9200"

mkdir -p elasticsearch/data
mkdir -p mongo/data
mkdir -p filebeat/data
mkdir -p graylog/ids

# When running i detached mode (-d) we get a problem when registering the GELFTCPInput in
# linux. Therefore we run it like this.
docker-compose up mongo elasticsearch graylog > /dev/null &

# Wait a bit to launch the three containers
sleep 5

# Wait for Elasticsearch to start
echo -n Waiting for Elasticsearch to start...
until curl -s $ES_URL -o /dev/null; do
    sleep 1
    echo -n .
done
echo

# Add mapping template
echo "Adding index template to Elasticsearch"
curl -s -H 'Content-Type: application/json' \
     -X PUT  "$ES_URL/_template/logs_status_and_audit_template" \
     -d @elasticsearch/logs_status_and_audit_template.json -o /dev/null

# Set up Graylog
python graylog_setup.py

docker-compose stop mongo elasticsearch graylog
