- pipeline.id: application_logs
  path.config: "/usr/share/logstash/pipeline/application_logs.conf"
  pipeline.workers: 1
  queue.type: persisted
  queue.max_bytes: 4gb
  queue.checkpoint.writes: 1
- pipeline.id: access_logs
  path.config: "/usr/share/logstash/pipeline/access_logs.conf"
  pipeline.workers: 1
  queue.type: persisted
  queue.max_bytes: 4gb
  queue.checkpoint.writes: 1