#!/bin/bash

mkdir -p elasticsearch/data
mkdir -p mongo/data
mkdir -p filebeat/data

# When running i detached mode (-d) we get a problem when registering the GELFUDPInput in linux.
# Therefore we run it like these, at the cost of seeing lots of logs in the console.
docker-compose up mongo elasticsearch graylog &

# Wait for graylog to come up
sleep 45

# Add mapping template
curl -X PUT -u elastic:changeme "localhost:9200/_template/logs_status_and_audit_template" -H 'Content-Type: application/json' -d @elasticsearch/logs_status_and_audit_template.json
echo

python graylog_setup.py

docker-compose stop mongo elasticsearch graylog

# Skriv om at det er nødvendig å gjøre det manuelt. Manglende API-dokumentasjon Skriv om hva pipelinen gjør og hvorfor. Også om feiling av meldinger ved sending, ...