#!/bin/bash

mkdir -p elasticsearch/data
mkdir -p mongo/data
mkdir -p filebeat/data

# When running i detached mode (-d) we get a problem when registering the GELFUDPInput in linux.
# Therefore we run it like these, at the cost of seeing lots of logs in the console.
docker-compose up mongo elasticsearch graylog &

# Wait for graylog to come up
sleep 45

# Add mapping template
curl -X PUT -u elastic:changeme "localhost:9200/_template/access_logs_template" -H 'Content-Type: application/json' -d @elasticsearch/access_template.json
echo

python graylog_setup.py

docker-compose stop mongo elasticsearch graylog
