version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/dead_letter_queue:/usr/share/logstash/data/dead_letter_queue
    ports:
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat_application_logs:
    build:
      context: filebeat_application_logs/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./filebeat_application_logs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/:/mnt/logs:ro
      - ./filebeat_application_logs/data/:/usr/share/filebeat/data/
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash

  filebeat_access_logs:
    build:
      context: filebeat_access_logs/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./filebeat_access_logs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/:/mnt/logs:ro
      - ./filebeat_access_logs/data/:/usr/share/filebeat/data/
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash

networks:

  elk:
    driver: bridge
